# -*- coding: utf-8 -*-
"""CS121Gen_Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xrL0qcFQf6lxrP65ZoY26XL3tn0HiRph
"""

import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt

"""## Generate content table"""

netflix_df = pd.read_csv('https://raw.githubusercontent.com/anika24/CS121-Final-Project/main/raw-data/netflix_titles.csv')
amazon_prime_df = pd.read_csv('https://raw.githubusercontent.com/anika24/CS121-Final-Project/main/raw-data/amazon_prime_titles.csv')
disney_df = pd.read_csv('https://raw.githubusercontent.com/anika24/CS121-Final-Project/main/raw-data/disney_plus_titles.csv')
hulu_df = pd.read_csv('https://raw.githubusercontent.com/anika24/CS121-Final-Project/main/raw-data/hulu_titles.csv')

def update_cols(df):
  del df['show_id']
  del df['cast']
  del df['country']
  del df['date_added']
  del df['description']
  del df['duration']
  df = df.rename(columns={'type': 'content_type', 'rating': 'viewability', 'listed_in': 'genres'}, inplace = True)

datasets = [netflix_df, amazon_prime_df, disney_df, hulu_df]
for df in datasets:
  update_cols(df)

netflix_df['on_netflix'] = 1
amazon_prime_df['on_amazon_prime'] = 1
disney_df['on_disney_plus'] = 1
hulu_df['on_hulu'] = 1

print(amazon_prime_df.columns.values)
print(netflix_df.columns.values)
print(disney_df.columns.values)
print(hulu_df.columns.values)

# first, merge hulu and netflix into df2 and fix the resulting df2's columns
df2 = pd.merge(hulu_df, netflix_df, on=['title', 'release_year', 'content_type'], how = 'outer')
df2['on_hulu'].fillna(0, inplace = True)
df2['on_netflix'].fillna(0, inplace = True)
df2['viewability_x'].fillna(df2['viewability_y'], inplace = True)
df2['genres_x'].fillna(df2['genres_y'], inplace = True)
df2['director_x'].fillna(df2['director_y'], inplace = True)
del df2['viewability_y']
del df2['genres_y']
del df2['director_y']
df2 = df2.rename(columns={'director_x': 'director', 'viewability_x': 'viewability', 'genres_x': 'genres'})

# next, merge df2 with amazon prime df into df3 and fix the resulting df3's columns
df3 = pd.merge(df2, amazon_prime_df, on=['title', 'release_year', 'content_type'], how = 'outer')
df3['on_hulu'].fillna(0, inplace = True)
df3['on_netflix'].fillna(0, inplace = True)
df3['on_amazon_prime'].fillna(0, inplace = True)
df3['viewability_x'].fillna(df3['viewability_y'], inplace = True)
df3['genres_x'].fillna(df3['genres_y'], inplace = True)
df3['director_x'].fillna(df3['director_y'], inplace = True)
del df3['viewability_y']
del df3['genres_y']
del df3['director_y']
df3 = df3.rename(columns={'director_x': 'director', 'viewability_x': 'viewability', 'genres_x': 'genres'})

df3

# finally, merge df3 with disney+ df into d4 and fix the resulting df4's columns
df4 = pd.merge(df3, disney_df, on = ['title', 'release_year', 'content_type'], how = 'outer')
df4['on_hulu'].fillna(0, inplace = True)
df4['on_netflix'].fillna(0, inplace = True)
df4['on_amazon_prime'].fillna(0, inplace = True)
df4['on_disney_plus'].fillna(0, inplace = True)
df4['viewability_x'].fillna(df4['viewability_y'], inplace = True)
df4['genres_x'].fillna(df4['genres_y'], inplace = True)
df4['director_x'].fillna(df4['director_y'], inplace = True)
del df4['viewability_y']
del df4['genres_y']
del df4['director_y']
df4 = df4.rename(columns={'director_x': 'director', 'viewability_x': 'viewability', 'genres_x': 'genres'})
df4['content_id'] = (df4.index + 1)
df4['on_hulu'] = df4['on_hulu'].astype(int)
df4['on_netflix'] = df4['on_netflix'].astype(int)
df4['on_amazon_prime'] = df4['on_amazon_prime'].astype(int)
df4['on_disney_plus'] = df4['on_disney_plus'].astype(int)

# reorder columns
content_df = df4[['content_id', 'content_type', 'title', 'release_year', 'director', 'viewability', 'genres', 'on_hulu', 'on_netflix', 'on_amazon_prime', 'on_disney_plus']]

content_df

content_df.to_csv('content.csv')

"""## Generate ratings table"""

content = []
ratings = []
num_ratings = []
service = []
for i in range(len(content_df)):
  row = content_df.iloc[i]
  id = row['content_id']
  if row['on_hulu']:
    ratings.append(round(random.uniform(1, 10), 1))
    num_ratings.append(round(random.uniform(5, 5000)))
    service.append(4)
    content.append(id)
  if row['on_netflix']:
    ratings.append(round(random.uniform(1, 10), 1))
    num_ratings.append(round(random.uniform(5, 5000)))
    service.append(1)
    content.append(id)
  if row['on_amazon_prime']:
    ratings.append(round(random.uniform(1, 10), 1))
    num_ratings.append(round(random.uniform(5, 5000)))
    service.append(2)
    content.append(id)
  if row['on_disney_plus']:
    ratings.append(round(random.uniform(1, 10), 1))
    num_ratings.append(round(random.uniform(5, 5000)))
    service.append(3)
    content.append(id)

df_ratings = pd.DataFrame({'rating_id': list(range(1, len(content)+1)),
                           'content_id': content,
                           'service_id': service,
                           'rating': ratings, 
                           'num_ratings': num_ratings})

df_ratings

df_ratings.to_csv('content_ratings.csv')